<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>opm</string>
		<string>opm.txt</string>
	</array>
	<key>name</key>
	<string>Orbital Parameter Message</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>COSPAR ID</string>
			<key>match</key>
			<string>([0-9]{4}\-[0-9]{3}[A-Z]{1,3})</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Match valid time systems</string>
			<key>match</key>
			<string>(TIME_SYSTEM)(\s*=\s*)(GMST|GPS|MET|MRT|SCLK|TAI|TCB|TDB|TCG|TT|UT1|UTC)($)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Colour non-standard time systems differently (but not invalid!)</string>
			<key>match</key>
			<string>(TIME_SYSTEM)(\s*=\s*)(.*$)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Match valid reference frames</string>
			<key>match</key>
			<string>(REF_FRAME)(\s*=\s*)(EME2000|GCRF|GRC|ICRF|ICRF2000|ITRF-93|ITRF-97|MCI|TDR|TEME|TOD)($)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Colour non-standard reference frames differently (but not invalid!)</string>
			<key>match</key>
			<string>(REF_FRAME)(\s*=\s*)(.*$)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Match valid reference frames</string>
			<key>match</key>
			<string>((?:MAN|COV)_REF_FRAME)(\s*=\s*)(RSW|RTN|TNW|EME2000|GCRF|GRC|ICRF|ICRF2000|ITRF-93|ITRF-97|MCI|TDR|TEME|TOD)($)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Colour non-standard reference frames differently (but not invalid!)</string>
			<key>match</key>
			<string>((?:MAN|COV)_REF_FRAME)(\s*=\s*)(.*$)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Colour values as strings</string>
			<key>match</key>
			<string>(CENTER_NAME|ORIGINATOR)(\s*=\s*)(.*$)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Format dates where applicable in YYYY-MM-DDTHH:MM:SS[.dddddd][Z] or YYYY-DDDTHH:MM:SS[.dddddd][Z] form</string>
			<key>match</key>
			<string>(EPOCH|CREATION_DATE|REF_FRAME_EPOCH|MAN_EPOCH_IGNITION)(\s*=\s*)((?:[0-9]{4}-(?:[0-9]{2}-[0-9]{2}|[0-9]{3})T[0-9]{2}:[0-9]{2}:[0-9]{2})(?:\.[0-9]+)?Z?)($)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Format invalid dates</string>
			<key>match</key>
			<string>(EPOCH|CREATION_DATE|REF_FRAME_EPOCH|MAN_EPOCH_IGNITION)(\s*=\s*)(.*$)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Format user defined parameters. Variable name will be formatted differently if colour scheme supports it.</string>
			<key>match</key>
			<string>(USER_DEFINED_)(\w+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ARG_OF_PERICENTER|CCSDS_OPM_VERS|CENTER_NAME|COV_REF_FRAME|CREATION_DATE|CX_DOT_X|CX_DOT_X_DOT|CX_DOT_Y|CX_DOT_Z|CX_X|CY_DOT_X|CY_DOT_X_DOT|CY_DOT_Y|CY_DOT_Y_DOT|CY_DOT_Z|CY_X|CY_Y|CZ_DOT_X|CZ_DOT_X_DOT|CZ_DOT_Y|CZ_DOT_Y_DOT|CZ_DOT_Z|CZ_DOT_Z_DOT|CZ_X|CZ_Y|CZ_Z|DRAG_AREA|DRAG_COEFF|DRAG_COEFF|ECCENTRICITY|EPOCH|GM|INCLINATION|MAN_DELTA_MASS|MAN_DURATION|MAN_DV_1|MAN_DV_2|MAN_DV_3|MAN_EPOCH_IGNITION|MAN_REF_FRAME|MASS|MEAN_ANOMALY|OBJECT_ID|OBJECT_NAME|ORIGINATOR|RA_OF_ASC_NODE|REF_FRAME|REF_FRAME_EPOCH|SEMI_MAJOR_AXIS|SOLAR_RAD_AREA|SOLAR_RAD_COEFF|TIME_SYSTEM|TRUE_ANOMALY|X|X_DOT|Y|Y_DOT|Z|Z_DOT)\b</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[|\])</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|-|\+|\*{1,2}|/)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(COMMENT.*)</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match integers or floats with optional exponent</string>
			<key>match</key>
			<string>\b([0-9]+(\.[0-9]+)?(e[+\-]?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.opm.ascii</string>
	<key>uuid</key>
	<string>920311c4-c2c0-4fa6-a9b7-09265b71de6b</string>
</dict>
</plist>
